### ISSUE TITLE
NPC 생성

### ISSUE THREAD

**Issue by jwvg0425** [jwvg0425/ProjectArthas#103]
최상위 클래스 생성 (자판기 컴퓨터 등등)

**Comment by agebreak** [comment]
음? NPC 생성은 최하위 순위가 아닐까?? 
NPC 없이 UI 로만 뛰워도 우선은 게임은 되니까.

**Comment by ghost** [comment]
자판기가 상점 NPC 같은 개념이라 NPC 최상위 클래스 정도는 만들고 자판기만 가볍게 구현해볼 생각으로 이슈를 걸었던 것 같아요 ㅎㅎㅎ
