### ISSUE TITLE
Release #1 피드백

### ISSUE THREAD

**Issue by zeliard** [jwvg0425/ProjectArthas#122]
1. 스터디
   OK
2. 마일스톤
   OK
3. 배포
   깔끔하게 잘 했음. 업데이트 노트도 잘 썼고..
   그런데 표현이 애매한 것이 있음 
   - "게임 데이터(.json파일)로부터 내용 읽어와 구조체에 저장하는 기능 구현" -> 이렇게 말하면, 보통 게임 콘텐츠 데이터를 읽어와서 구조체로 맵핑해서 게임 로직에서 사용하는 것으로 생각되는게 일반적임.. 

내용을 보니까 게임 리소스에 대한 것을 읽어오는 config파일 정도로 보이는데??

**Comment by jwvg0425** [comment]
.json으로부터 데이터 읽어오는 기능 설명이 미흡했던 것 같습니다. 말씀하신 부분 명확하게 수정하여 다시 커밋했습니다.
