### ISSUE TITLE
커밋 메세지 남길때..

### ISSUE THREAD

**Issue by zeliard** [jwvg0425/ProjectArthas#139]
지금 커밋 메세지들 보면 의미가 없거나 장난(?)으로 남기고 있는데...
이렇게 계속하면 빠따 맞는다.
날씨도 추운데 h스퀘어 옥상 연병장에 집합하기 싫으면, 커밋 메세지는 간결하되 뭘 고쳤는지 핵심 내용을 포함하도록 할  것.

**Comment by ghost** [comment]
넵!!! 시정하겠습니다~!
