### ISSUE TITLE
FMOD 의존성 문제 및 필터 문제

### ISSUE THREAD

**Issue by zeliard** [jwvg0425/ProjectArthas#144]
1. FMOD 없다고 빌드 안되는데, cocos2d에 이미 포함된 사운드모듈 없는가? 
   fmod를 직접 쓸일이 없을텐데?
2. 프로젝트 열어보면 필터가 없는데, 필터는 따로 업로드 안한건지.. 아니면 안쓰는건지?
   소스파일 분류에 필터를 적극 활용하도록.

**Comment by jwvg0425** [comment]
1. 갓 준철님의 조언으로 FMOD 안 쓰고 하는 방법을 알게 돼서 FMOD 삭제했습니다.
2. 각자 프로젝트에서 자기가 편한 방식으로 필터를 관리하고 있는 상황이라 필터는 업로드하지 않았습니다. 릴리즈할 때는 분류 편하게 필터 포함해서 업로드하도록 하겠습니다.

**Comment by pjc0247** [comment]
난모야
