### ISSUE TITLE
Thing Class 구현

### ISSUE THREAD

**Issue by abiles** [jwvg0425/ProjectArthas#15]
최대한 빨리 

최상위 class입니다.

**Comment by ozt88** [comment]
Thing 을 Component로 만들었음

**Comment by ozt88** [comment]
Thing 설계 포기한 이유. Component가 하위 Component의 집합 기능도 가능해야한다. 따로  Thing을 만들어도 기존 Component가 하위 Component의 집합역할을 할 수 있기때문에 쓸데없이 중복된다. 따라서 Thing대신 Component로 모든 게임 오브젝트들을 표현할 수 있다고 생각했다.
