### ISSUE TITLE
drag and drop 구현 

### ISSUE THREAD

**Issue by abiles** [jwvg0425/ProjectArthas#72]
FSM으로 만들면 편함

**Comment by agebreak** [comment]
드래그엔 드랍은 실제 만들어보면.. 의외로 복잡한 FSM과 이벤트를 가지지.. 훗훗훗

**Comment by ghost** [comment]
이전 프로토타입에서 간단하게 한 번 만들어 봤는데 뒤에 아이템 로직만 없다 뿐이었지 UI에서 작동하는 건 성공했었어요 ㅎㅎㅎ 이것보다 어제 회의에서 나온 '잡고 끌어서 휠처럼 넘기기'가 더 어려울 것 같아서 걱정이네요 ㅋㅋㅋㅋㅋ 일단 Cocostudio UI Editor도 참고해볼 계획입니다!

**Comment by agebreak** [comment]
잡고 끌어서 넘기기?? 아이폰 슬라이드 UI 같은건가?? 그건 만들기 쉬운데..?
